add_newline = false
format = "$battery$directory$git_branch$git_commit$git_state$git_status$package$golang$nodejs$python$rust$memory_usage$aws$status$jobs$line_break$character"

command_timeout = 2000

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€ "

[[battery.display]] 
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 60
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[character]
success_symbol = "[á—](bold green)"
error_symbol = "[á—](bold red)"

[git_status]
conflicted = " ïˆ‹ "
ahead = " ï¢ "
behind = " ï£ "
diverged = " ï—º "
untracked = " ï„¨ "
stashed = " ï…• "
modified = " ï„ª "
staged = " ï§ "
renamed = " ï¡ "
deleted = " âœ˜ "
